spring.application.name=WaterQualityBackend

# ==========================
# DATABASE CONFIGURATION (Supabase PostgreSQL)
# ==========================

# Database connection for Supabase PostgreSQL (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.cevghzamuzpfckazrbtk
spring.datasource.password=#Ganesh8088239071
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA CONFIGURATION
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# SERVER CONFIGURATION
# ==========================

server.port=8080

# ==========================
# LOGGING
# ==========================

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================
# GOOGLE OAUTH CONFIGURATION
# ==========================

google.client-id=1095651319432-8bciubb89jokk3089ud622eh9rsiloc0.apps.googleusercontent.com