spring.application.name=WaterQualityBackend

# ==========================
# DATABASE CONFIGURATION
# ==========================

spring.datasource.url=jdbc:mysql://localhost:3306/water_quality_monitoring?createDatabaseIfNotExist=true

spring.datasource.username=root

spring.datasource.password=Ganesh

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA CONFIGURATION
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================
# SERVER CONFIGURATION
# ==========================

server.port=8080

# ==========================
# LOGGING
# ==========================

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE